{% set name = "sentry-sdk" %}
{% set version = "2.66.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/get{{ name.split('-')[0] }}/{{ name.split('-')[0] }}-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5775b1bf806472c6c6fcd1d20d6b119cbbf0c60af96d8a954b73f53837adc52c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - urllib3 >=1.26.11
    - certifi
  run_constrained:
    - aiohttp >=3.5
    - anthropic >=0.16
    - arq >=0.23
    - asyncpg >=0.23
    - apache-beam >=2.12
    - bottle >=0.12.13
    - celery >=3
    - celery-redbeat >=2
    - chalice >=1.16.0
    - clickhouse-driver >=0.2.0
    - django >=1.8
    - falcon >=1.4
    - fastapi >=0.79.0
    - flask >=0.11
    - blinker >=1.1
    - grpcio >=1.21.1
    - protobuf >=3.8.0
    - httpcore ==1.*
    - httpx >=0.16.0
    - huey >=2
    - huggingface_hub >=0.22
    - langchain >=0.0.210
    - langgraph >=0.6.6
    - launchdarkly-server-sdk >=9.8.0
    - litellm >=1.77.5,!=1.82.7,!=1.82.8
    - litestar >=2.0.0  # extra:litestar
    - mcp >=1.15.0
    - loguru >=0.5
    - openai >=1.0.0
    - tiktoken >=0.3.0
    - openfeature-sdk >=0.7.1
    - opentelemetry-distro >=0.35b0
    - pydantic-ai >=1.0.0
    - pymongo >=3.1
    - pyspark >=2.4.4
    - quart >=0.16.1
    - blinker >=1.1  # extra:blinker
    - rq >=0.6
    - sanic >=0.8
    - sqlalchemy >=1.2
    - starlette >=0.19.1
    - starlite >=1.48
    - statsig >=0.55.3
    - tornado >=6
    - UnleashClient >=6.0.1
    - google-genai >=1.29.0

# Need to test only the pkg directly, not dependencies which can possibly use this pkg.
{% set ignore_tests = " --ignore=tests/integrations" %}
# Tests failed randomly on the CI
{% set ignore_tests = ignore_tests + " --ignore=tests/profiler/test_continuous_profiler.py" %}
# >   assert len(envelopes) == 1
# E   assert 0 == 1
# E    +  where 0 = len([])
{% set deselect_tests = " --deselect=tests/test_dsc.py::test_dsc_issue" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_dsc.py::test_dsc_issue_with_tracing" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_dsc.py::test_dsc_issue_twp" %}
# >   raise AssertionError("1 logs was never flushed after 10 seconds")
# E   AssertionError: 1 logs was never flushed after 10 seconds
{% set deselect_tests = deselect_tests + " --deselect=tests/test_logs.py::test_auto_flush_logs_after_100" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_logs.py::test_log_user_attributes" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_logs.py::test_auto_flush_logs_after_5s" %}
# >   assert Scope.last_event_id() is not None
# E   assert None is not None
# E    +  where None = last_event_id()
# E    +    where last_event_id = Scope.last_event_id
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scope.py::test_merging" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scope.py::test_last_event_id" %}
# >   (event,) = events
# E   ValueError: not enough values to unpack (expected 1, got 0)
{% set deselect_tests = deselect_tests + " --deselect=tests/test_full_stack_frames.py::test_full_stack_frames_default" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_full_stack_frames.py::test_full_stack_frames_enabled" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_sessions.py::test_basic" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_sessions.py::test_aggregates" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_feature_flags.py::test_featureflags_integration" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_spotlight.py::test_spotlight_envelope" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_utils.py::test_default_release" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scrubber.py::test_stack_var_scrubbing" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scrubber.py::test_breadcrumb_extra_scrubbing" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scrubber.py::test_custom_denylist" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scrubber.py::test_scrubbing_doesnt_affect_local_vars" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scrubber.py::test_recursive_scrubber_does_not_override_original" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_socks_proxy" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_ignore_errors" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_include_local_variables_enabled" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_include_local_variables_disabled" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_include_source_context_enabled" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_include_source_context_disabled" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_function_names" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_nan" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_cyclic_frame_vars" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_databag_depth_stripping" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_databag_string_stripping" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_databag_breadth_stripping" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_chained_exceptions" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_broken_mapping" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_mapping_sends_exception" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_object_sends_exception" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_errno_errors" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_non_string_variables" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_dict_changed_during_iteration" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_custom_repr_on_vars" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_error_sampler" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_basics.py::test_dedupe_event_processor_drop_records_client_report" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_basics.py::test_dedupe_doesnt_take_into_account_dropped_exception" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_basics.py::test_staticmethod_instance_tracing" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_basics.py::test_classmethod_instance_tracing" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_basics.py::test_last_event_id" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/profiler/test_continuous_profiler.py::test_continuous_profiler_auto_start_and_stop_sampled" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/profiler/test_transaction_profiler.py::test_profile_captured" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_basics.py::test_notes" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/test_basics.py::test_stacktrace_big_recursion" %}
# assert ('socks' in "<class 'httpcore.asyncconnectionpool'>") == True
#  +  where "<class 'httpcore.asyncconnectionpool'>" = <built-in method lower of str object at 0xffff8dfd7000>()
{% set deselect_tests = deselect_tests + " --deselect=tests/test_client.py::test_async_socks_proxy" %}
# IndexError: list index out of range
{% set deselect_tests = deselect_tests + " --deselect=tests/test_scope.py::test_set_user" %}
# E           AssertionError: assert {'sentry.op': 'gen_ai.invoke_agent', 'sentry.origin': 'manual', ....
{% set deselect_tests = deselect_tests + " --deselect=tests/tracing/test_decorator.py::test_span_templates_ai_dicts" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/tracing/test_decorator.py::test_span_templates_ai_objects" %}
# WIN path errors not found file with "/", neeeds "\\".
{% set deselect_tests = deselect_tests + " --deselect=tests/new_scopes_compat/test_new_scopes_compat_event.py::test_event" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/utils/test_general.py::test_abs_path" %}  # [win]
{% set deselect_tests = deselect_tests + " --deselect=tests/utils/test_general.py::test_filename" %}  # [win]
# >       assert len(profile_chunks) > 0
# E       assert 0 > 0
# E        +  where 0 = len([])
{% set deselect_tests = deselect_tests + " --deselect=tests/tracing/test_span_streaming.py::test_segment_span_has_profiler_id" %}  # [osx]
# E       AssertionError: profiler should have stopped
# E       assert '5ee37a29e25a4b69a49a195dbf49768e' is None
# E        +  where '5ee37a29e25a4b69a49a195dbf49768e' = get_profiler_id()
{% set deselect_tests = deselect_tests + " --deselect=tests/tracing/test_span_streaming.py::test_profile_stops_when_segment_ends" %}  # [osx]

test:
  source_files:
    - tests
  imports:
    - sentry_sdk
  commands:
    - pip check
    - python -m pytest -vv tests {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest >=6.0.0
    - brotli-python
    - pytest-localserver
    - jsonschema
    - pytest-asyncio
    - executing
    - httpcore
    - httpx
    - h2

about:
  home: https://github.com/getsentry/sentry-python
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The new Python SDK for Sentry.io
  description: |
    The new Python SDK for Sentry.io
  doc_url: https://docs.sentry.io/quickstart/?platform=python
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - alippai
    - dgasmith
    - djsutherland
