travis:
  secure:
    BINSTAR_TOKEN: hCWm5opUCF5hame06jBJkRUDq0bLaQQyQ7jov8JEhqrv1IYw0W0erfnkY8wuiUmalR1VEqty9JjeEVddp0ucGm2nN86UPKu2O7u1nxmNvhtZFCUOUN3oimboiu7i/b/vuPaXCtNK1AKS/HPbi0VkDfUH3D9Qwhx8sXPQCywG8k6K1kZrKNiaT+qyCvwFfDcBuyxljUeJnjozHvaDb7XMds0XrbcViWAKhAyJupYYOBKPe08sp34h5wLnZY/q+IRDA5iYFiKLAPJV+Q3nppkM9z+skrdGvOERISd0aOEJyNx+iVhmtnHDL3SQq54NrFdMuix1wmGEBggzOoE01fgdJPoPv0/3yuOqW4/hYZtbyApEgTK1WFq8GP4otu/90np/7IFtTXVgbKAxxCB9fqOK+WADU1DubMDnmdaRRGvQMK8OtkgeqPLftOR4MxDuO2gCFUBqjbeOEprchkGn8gqC0DvBvvTvPLqwYtJXY/3ihfpTTDcB2NFQYgegtA3CEBSI+oQSHEzazQ//pit+9cODwVzVbMOUsSKIvYPZGsz8I7nBwLGhJ+4BFtj7Mr9LYkAL7Ppx4flF4ezzyEAeKqgkmiW3OsdrbzojJlls0H+LksEMbeoThMVZ2imP7bWp73Ud0orVCBxGbfm9F4bqgLdKvpI9WfFBzZkV1/XRX+7dXdc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
